### ISSUE TITLE
프로젝트 파일 초기 세팅

### ISSUE THREAD

**Issue by dev-muuu** [PomeTeam/POME_iOS#1]
## 💡 issue
프로젝트 파일 초기 세팅

## 📝 todo
- [x] gitignore 파일 추가
   - [x] ds_store 추가
   - [x]  xccconfig 추가
- [x] AppKey 파일 추가
- [x] 폴더링 구조화
- [x] podfile 추가
- [x] storyboard 분리
- [x] dev 브랜치 메인 설정
- [x]  깃 이슈 템플릿 추가
