### ISSUE TITLE
TextField Delegate 및 버튼 활성화 구현

### ISSUE THREAD

**Issue by dev-muuu** [PomeTeam/POME_iOS#107]
## 💡 issue
TextField Delegate 및 버튼 활성화 구현

## 📝 todo
- [x]  목표 등록 text field
- [x]  목표 등록 버튼
- [x]  기록 등록 text field
- [x]  기록 등록 버튼
