### ISSUE TITLE
하단 친구 탭 UI 및 기능 구현

### ISSUE THREAD

**Issue by dev-muuu** [PomeTeam/POME_iOS#11]
## 💡 issue
하단 친구 탭 UI 및 기능 구현

## 📝 todo
- [x]  CollectionViewCell 기본 UI
- [x]  CollectionView 기본 UI
- [x]  TableViewCell 기본 UI
- [x]  TableView 기본 UI
- [x] #30
- [x]  TableViewCell shadow 적용
- [x]  CollectionView 전체/친구 목록 구분
- [x]  CollectionViewCell Select/UnSelect 구분
- [x]  공감 리스트 BottomSheet
- [x]  친구 없을 경우 EmptyView
- [x]  이모지 등록 후 toast message
- [x]  친구 글 상세보기
- [x]  tableview cell 수정 UI 반영
