### ISSUE TITLE
마이페이지 유저 정보 출력

### ISSUE THREAD

**Issue by gom1n** [PomeTeam/POME_iOS#150]
## 💡 issue
마이페이지 유저 정보 출력

## 📝 todo
- [x]  마이페이지 프로필 이미지 & 닉네임
- [x]  마이페이지 - 설정
- [x]  마이페이지 - 친구 관리
  - [x] 내 친구 목록 조회
  - [x] 친구 삭제
