### ISSUE TITLE
기록탭 관련 API 연결

### ISSUE THREAD

**Issue by gom1n** [PomeTeam/POME_iOS#155]
## 💡 issue
기록탭 관련 API 연결

## 📝 todo
- [x]  상단 목표 전체 조회
- [x]  목표 삭제하기
- [x]  목표 하나 조회
        - 목표가 존재하지 않을 때
        - 목표에 씀씀이가 존재하지 않을 때
        - 목표 일반 조회
        - 종료된 목표일 때
- [x]  마이페이지 > 목표 보관함 - 완료한 목표 전체 조회
- [x]  목표 종료하기
- [x] 목표 당 기록들 조회
        - 목표 response model - isEnd 추가
