### ISSUE TITLE
소비 기록/목표 데이터 시간 계산

### ISSUE THREAD

**Issue by dev-muuu** [PomeTeam/POME_iOS#165]
## 💡 issue
기록 데이터 시간 계산

## 📝 todo
- [x]  기록 생성 당일 여부 체크
- [x]  당일인 경우 분 단위/시간 단위 반환 메서드
- [x]  디데이 계산 메서드
