### ISSUE TITLE
남은 작업

### ISSUE THREAD

**Issue by gom1n** [PomeTeam/POME_iOS#181]
## 💡 issue
남은 작업들을 정리하고자... 

## 📝 todo
- [x]  약관 동의 상세 페이지 요청 
- [x] 기록탭 > 일주일이 지나지 않고 두번째 감정을 남기지 않은 기록에 대한 API 연결
- [x] 일주일이 지났고 두번째 감정을 남기지 않은 기록을 조회하는 API 연결
- [x] 최대 목표 개수 문의 > 목표 생성 시 워닝 시트 팝업
- [x] 기록 생성 시 목표 카테고리 
   - 종료 기한이 지난 목표도 기록 생성이 가능한 것인가? **`NO`**
   - 완료된 목표도 기록 생성이 가능한가? **`NO`**
- [x] 기록 탭 > 종료 기간이 지난 목표(깃발셀)의 기록들도 출력해야하는가?
- [x] 친구 탭 > 친구 추가 > 친구 추가 후 화면 전환 구분
- [x] 마이페이지 > 마시멜로 API 연결
- [x] 회원가입/로그인 > 인증번호 불일치 오류메세지 출력
- [x] 회원가입 > 프로필 이미지를 이미 선택했을 시 액션시트 팝업
- [x] 기록탭 > 목표 종료 > 케이스 3가지 나누기
   - 7일이전 기록 있을 때 -> 아직 돌아보지 않은 기록이 있어요 바텀시트 띄우고 & 종료 페이지 진입 불가
   - 7일 이전 기록은 없으나 2차감정 기록을 하지 않았을 때 -> 아직 돌아보지 않은 기록이 있어요 바텀시트 띄우기 & 종료 페이지 진입 불가
   - 모든 감정기록 완료했을 때 -> 종료페이지 진입
- [x] 목표 종료 > 목표 종료하기 버튼 수정
- [x] 기록탭 페이징 구현
- [x] 로그인 > '인증번호가 오지 않나요?'
- [x] 탈퇴 api 수정
- [x] 알림설정 뷰 없애기
- [x] 테이블뷰 > 로딩 뷰
- [x] 네트워크 에러 팝업 뷰
