### ISSUE TITLE
기록 삭제/수정/리액션 등록시 ResponseModel로 수정된 기록 데이터 받아오기

### ISSUE THREAD

**Issue by dev-muuu** [PomeTeam/POME_iOS#212]
## 💡 issue
기록 삭제/수정/리액션 등록시 ResponseModel로 수정된 기록 데이터 받아오기

## 📝 todo
- [x]  회고탭 - 기록 삭제
- [x]  회고탭 - 기록 리액션
- [x]  회고탭 - 기록 수정
- [x]  회고탭 - 기록 상세 > 리액션
- [x]  회고탭 - 기록 상세 > 수정
- [x]  회고탭 - 기록 상세 > 삭제
- [x]  친구탭 - 기록 리액션
- [x]  친구탭 - 기록 상세 > 리액션
