### ISSUE TITLE
UITextView + 글자 수 카운팅 레이아웃 및 세부 기능 점검

### ISSUE THREAD

**Issue by dev-muuu** [PomeTeam/POME_iOS#214]
## 💡 issue
TextView 레이아웃이랑 디자인 등 이상한 부분들이 있어서 점검을 해봅니다..
 ( + 데이터 바인딩할 때 글자색상도 )

## 📝 todo
- [x] editingMode 적용
- [x] 글자 수 초과시 빨간 글씨로
- [x] 폰트 이상한거 같은데 확인해보기
- [x]  상단 레이아웃 offset 확인
