### ISSUE TITLE
1차 QA 수정 - 디자인 by 쑤야

### ISSUE THREAD

**Issue by dev-muuu** [PomeTeam/POME_iOS#235]
## 💡 issue
1차 QA를 바탕으로 UI를 수정합니다.

## 📝 todo
- [x] 달력 사이즈 조정 > mini 버전인 경우 셀 6개가 최대로 뜸
- [x] 목표 태그 셀 크기 반환 메서드 추가
- [x] 하단 탭바 그림자 설정
- [x] 감정 태그 텍스트 컬러 설정
- [x] 목표 설정 > 금액` , `표시
- [x] 기록 생성 > 금액 ` , `표시
- [x] 텍스트 필드 focus시 백그라운드 색상 변경
- [x] 3D 컴포넌트 Asset 파일 교체 > 눌린다는데... 내 눈엔 똑같은걸....🥹
- [x] 바텀시트 오버레이 컬러
- [x] 헤더뷰 아이콘 교체 > 이후에도 컬러값 안맞을 경우 tint값 조정
