### ISSUE TITLE
1차 QA 수정 - 기획 by 쑤야

### ISSUE THREAD

**Issue by dev-muuu** [PomeTeam/POME_iOS#242]
## 💡 issue

1차 QA 결과를 반영해 기능을 수정합니다. 

## 📝 todo
- [x]  목표 기간 설정 수정
   + 시작 > 종료 > 시작(종료보다 훨씬 이전으로 선택한 경우)
   + 시작 날짜 선택 이후 VC에서 유효성 검사 거치기
   + 에러 메시지 띄우기
- [x]  회고탭 내 기록 리액션 못 남김 > 리액션 일단 보류 + 회의 이후 서버 요청
- [x]  회고탭 리액션 관련 케이스 및 데이터 바인딩 수정
- [x]  회고탭 상세 보기 삭제
   + 회고탭에서 전체 내용 다 보여주기 (더보기 버튼 X)
- [x]  친구탭 리액션 1개인 경우 + 1 띄우기 > 리액션 일단 보류 + 회의 이후 서버 요청
- [x]  친구탭 상세 보기 삭제
   + 친구탭에서 전체 내용 다 보여주기 (더보기 버튼 X)
