### ISSUE TITLE
친구 추가 페이지 UI 구현

### ISSUE THREAD

**Issue by gom1n** [PomeTeam/POME_iOS#29]
## 💡 issue
친구 추가 페이지 UI 구현

## 📝 todo
- [x] '회원가입 완료!' 페이지
- [x] 친구 추가 페이지
     - [x] 초기 출력 - 검색창 제작
     - [x] 검색 결과
     - [x] 추가 완료
     - [x] 결과 없음
