### ISSUE TITLE
감정 FloatingView UI 및 기능 구현

### ISSUE THREAD

**Issue by dev-muuu** [PomeTeam/POME_iOS#30]
## 💡 issue
감정 FloatingView UI 및 기능 구현

## 📝 todo
- [x]  FloatingView Shadow 적용
- [x]  FloatingView cell별 레이아웃 높이 
- [x]  FloatingView 밖 영역 클릭시 view dismiss
- [x]  FloatingView 안의 영역 클릭시 dismiss 불가
- [x]  TableViewCell emoji 추가버튼 클릭 -> delegate method
- [x]  CollectionViewCell select ->  TableViewCell data attach
