### ISSUE TITLE
[CI/CD] Github Actions을 이용한 CI/CD (1)

### ISSUE THREAD

**Issue by gom1n** [PomeTeam/POME_iOS#313]
## 💡 issue
POME Github Actions을 이용한 CI/CD - 크게 두 가지로 작업하려합니다.
1. Github Actions 를 이용한 **xcode build & test** 자동화
2. Github Actions 를 이용한 **TestFlight 업로드** 자동화
잘 됐으면 좋겠다....^^....

## 📝 todo
- [x]  예비 TestCase 추가
- [x] Github Action Workflow 추가
- [x] yml 파일 작성
- [x] (에러 발생 시) OS 버전 제대로 확인
