### ISSUE TITLE
[FEATURE] Singleton + Observer를 활용한 데이터 전달

### ISSUE THREAD

**Issue by dev-muuu** [PomeTeam/POME_iOS#320]
## 💡 issue
RxSwift Observer를 활용한 데이터 전달
기록과, 목표 각각 싱글톤 인스턴스를 생성해 관리합니다. 

## 📝 todo
- [x] 기록 생성 > 기록 탭 전달
- [x] 목표 생성 > 기록 / 회고탭 전달
- [x] 목표 삭제 > 기록 / 회고탭 전달
- [x] 2번째 감정 남김 > 회고탭 전달 / 기록탭 전달
