### ISSUE TITLE
[BUG] Firebase Crashlytics 등록

### ISSUE THREAD

**Issue by gom1n** [PomeTeam/POME_iOS#328]
## 💡 issue
정확한 버그 원인 분석을 위해 app을 Firebase Crashlytics에 등록합니다.

## 📝 todo
- [x]  Firebase 프로젝트 생성
- [x] pod 추가 및 설치
- [x] xcode 빌드 환경 설정
