### ISSUE TITLE
[REFACTOR] 마이페이지 리팩토링

### ISSUE THREAD

**Issue by gom1n** [PomeTeam/POME_iOS#330]
## 💡 issue
마이페이지 리팩토링

## 📝 todo
- [x]  Clean Architecture
- [x]  RxSwift
- [ ] 마이페이지
- [ ] 완료한 목표 조회 페이지
- [ ] 친구 관리 페이지
- [ ] 마이페이지 > 설정 > 로그아웃
- [ ] 마이페이지 > 설정 > 탈퇴하기
