### ISSUE TITLE
기록탭 - Empty

### ISSUE THREAD

**Issue by gom1n** [PomeTeam/POME_iOS#41]
## 💡 issue
기록 비어있을 때 UI 구현

## 📝 todo
- [x]  목표 카테고리 바
- [x] '목표가 있어야 씀씀이를 기록할 수 있어요' 뷰
- [x] '일주일 씀씀이' 라벨
- [x] '감정을 다시 남겨주세요' 배너
- [x] '기록한 씀씀이가 없어요' Empty View
- [x] 목표 없는데 글쓰기 버튼 클릭 시, 바텀팝업창
