### ISSUE TITLE
기록탭 - Full

### ISSUE THREAD

**Issue by gom1n** [PomeTeam/POME_iOS#42]
## 💡 issue
기록탭 - Full 일 시 UI 구현

## 📝 todo
- [x]  목표 카드 뷰
   - [x] ProgressBar 커스텀
- [x] 더보기 버튼 클릭 시 메뉴 팝업
- [x] 삭제 팝업창
- [x] 씀씀이 뷰 (컬렉션뷰일 지 테이블뷰일 지 미정)
- [x] 목표 5개인데 목표추가 버튼 클릭 시 바텀팝업창
- [x] '아직은 감정을 기록할 수 없어요' 바텀팝업창
- [x] '감정을 남겨주세요' 터치 시 나오는 페이지 > Empty
- [x] '감정을 남겨주세요' 터치 시 나오는 페이지 > Full
