### ISSUE TITLE
마이페이지 UI 구현

### ISSUE THREAD

**Issue by gom1n** [PomeTeam/POME_iOS#75]
## 💡 issue
마이페이지 UI 구현

## 📝 todo
- [x]  마이페이지
- [x] 완료한 목표 > Empty
- [x] 완료한 목표 > Full
- [x] 완료한 목표 > 더보기 > 삭제 팝업창
- [x] 설정 페이지
    - [x]  구분선 커스텀
- [x] 알림설정 페이지
- [x] 친구관리 페이지
- [x] 친구 삭제 모달
- [x] 로그아웃 모달
