### ISSUE TITLE
기록 UI 

### ISSUE THREAD

**Issue by dev-muuu** [PomeTeam/POME_iOS#85]
## 💡 issue
기록 UI 
## 📝 todo
- [x]  기록 내용 UI
- [x]  기록 감정 UI
- [x]  작성 완료 UI
- [x]  작성 중단 모달 UI
- [x]  카테고리 BottomSheet UI
